# Final Project

You will be asked to download data by yourselves and answer several data science questions through this final project. This project has two parts.


## Part 1 (15 Points):

This part contains 10 different data science questions that you are asked to answer. You need to download the corresponding data and write code to process the data to answer these questions. For each question, you need to provide your code to anser this question, as well as final answers. Each question will be worth 1.5 points in this part. 


## Final Submission:

Your final submission will contain two files:

1. The first would be this notebook. You need to provide code for your answers as well as your answers. You also need to provide visualization and executive summary using Markdown in this notebook. 

2. The second is the html version of this notebook. 


## Part 1

First, you need to download the most recent datasets containing listing and reviews in **Los Angeles** from [insidearibnb.com](http://insideairbnb.com/get-the-data.html). (September,2019,detailed data)You will then need to provide the code as well as answers to the following questions.

**To make sure that you downloaded the right dataset, your solution to Question 1 should be:**
1. **Number of unique listings = 45053**
2. **Number of unique hosts = 26286**

### Question 1: How many unique listings are there in the LA dataset? How many unique hosts are there?
**Question 1 Answer:**

The number of unique listings in the LA dataset is 45053. And, the number of unique hosts are 26286 in the LA dataset.

In [ ]:

# You need to provide the code to answer the previous quesiton
# (you should also briefly explain your data structure -- 
# where do you put your data and how you get your data)
import pandas as pd
from pandasql import sqldf
import numpy as np

In [ ]:
listing_df=pd.read_csv('listings.csv',na_values={'NaN':'NA'})
uniq_listing=len(listing_df.drop_duplicates(keep='last', subset=['id']))
uniq_host=len(listing_df.drop_duplicates(keep='last', subset=['host_id']))
num_row,num_column=listing_df.shape

In [ ]:
print("Number of unique listings = ",listing_df.id.unique().shape[0])
print("Number of unique hosts = ",listing_df.host_id.unique().shape[0])

### Question 2: What is the mean, median, standard deviation, minimum and maximum of the number of listings per host in LA? (for each host, you only need to consider the listings from LA)
**Question 2 Answer:**

 The mean of the number of listings per host in LA =  1.7139541961500417  ,and the median of the number of listings per host in LA =  1.0 ;  The standard deviation of the number of listings per host in LA =  2.99918333694991 ; The minimum of the number of listings per host in LA =  1 ; The maximum of the number of listings per host in LA =  172

In [6]:
# You need to provide the code to answer the previous quesiton
A_df=listing_df.groupby(by='host_id').id.count().sort_values()
print(" The mean of the number of listings per host in LA = ",A_df.mean(),"\n",\
       "The median of the number of listings per host in LA = ",A_df.median(),"\n",\
       "The standard deviation of the number of listings per host in LA = ",A_df.std(),"\n",\
       "The minimum of the number of listings per host in LA = ",A_df.min(),"\n",\
       "The maximum of the number of listings per host in LA = ",A_df.max())

 The mean of the number of listings per host in LA =  1.7139541961500417 
 The median of the number of listings per host in LA =  1.0 
 The standard deviation of the number of listings per host in LA =  2.99918333694991 
 The minimum of the number of listings per host in LA =  1 
 The maximum of the number of listings per host in LA =  172


### Question 3: What is the average and standard deviation number of listings for a super host versus a non-super host? Does super host or non-super host have more listings on average?
**Question 3 Answer:**

The average for non-super host is 1.671021 and the standard deviation is 2.926276. As for super host, the average is 1.824264 and the standard deviation is 3.177892. Obviously, super host have more listing on average.

In [7]:
# You need to provide the code to answer the previous quesiton
B_df=listing_df.groupby(by=['host_is_superhost','host_id']).size().groupby(by=['host_is_superhost'])\
.agg([np.mean,np.std])
B_df

mean       std
host_is_superhost                    
f                  1.671021  2.926276
t                  1.824264  3.177892

### Question 4: What are the unique types of host verifications are there? (It doesn't matter if you include "None" or empty string as a type)
**Question 4 Answer:**

The unique types of host verifications are 
 ['email', 'phone', 'facebook', 'reviews', 'kba', 'jumio', 'government_id', 'offline_government_id', 'selfie', 'identity_manual', 'work_email', 'manual_online', 'manual_offline', 'google', 'sent_id', 'None', 'sesame', 'sesame_offline', 'photographer', 'zhima_selfie', 'weibo']

In [8]:
# You need to provide the code to answer the previous quesiton
uniq_lst = []
for i in listing_df["host_verifications"]:
    i = i.strip('[').strip(']').split(',')
    for j in i:
        j = j.strip(' \'')
        if j in uniq_lst:
            continue
        elif j != '':
            uniq_lst.append(j)
print("The unique types of host verifications are","\n",[i for i in uniq_lst])

The unique types of host verifications are 
 ['email', 'phone', 'facebook', 'reviews', 'kba', 'jumio', 'government_id', 'offline_government_id', 'selfie', 'identity_manual', 'work_email', 'manual_online', 'manual_offline', 'google', 'sent_id', 'None', 'sesame', 'sesame_offline', 'photographer', 'zhima_selfie', 'weibo']


### Question 5: What are the five most popular verification types of hosts? For each type of the top five verifications, how many percent of hosts verify that type?
**Question 5 Answer:**

The five most popular verification types are phone (the percentage is 0.996766), email (the percentage is 0.938370), reviews (the percentage is 0.688541), government_id (the percentage is 0.587689), jumio (the percentage is 0.433387).

In [9]:
# You need to provide the code to answer the previous quesiton
d1_df=listing_df.drop_duplicates(keep='last',subset=['host_id']).host_verifications
d1_df=d1_df.reset_index()

def get(row,t):
    row=row['host_verifications']
    row=row[1:len(row)-1]
    #rows=list(row.split(', '))
    if "'"+t+"'" in row:
        return 1
    else:
        return 0
    
for t in uniq_lst:
    d1_df[t]=d1_df.apply(lambda x: get(x,t),axis=1)

n=len(d1_df)
e1_df=d1_df.apply(lambda x:x.sum())[uniq_lst].apply(lambda x: x/n)
e1_df.sort_values(ascending=False).reset_index().rename(columns={'index':'verification',0:'percentage'})[0:5]

verification  percentage
0          phone    0.996766
1          email    0.938370
2        reviews    0.688541
3  government_id    0.587689
4          jumio    0.433387

### Question 6: What is the mean, standard deviation of the average price of a listing in Los Angles from 01/01/2020 to 03/01/2020 (inclusive)? (For listings that are not available in this time, you should not count them in the average price.)

**Question 6 Answer:**

The mean of the average price in LA from 01/01/2020 to 03/01/2020 is 254.778227. And the standard deviation of the average price of a listing in Los Angles from 01/01/2020 to 03/01/2020 is 684.755050

In [10]:
# You need to provide the code to answer the previous quesiton
calendar_df=pd.read_csv('calendar.csv')
calendar_df['new_date']=calendar_df.date.apply(lambda x: int(x[0:4]+x[5:7]+x[8:]))
calendar_df.head(5)
def str_to_int(row):
    if type(row) is not float:
        if len(row)>=9:
            num=row[1:-7]+row[-6:-3]
            return int(num)
        else:
            num=row[1:-3]
            return int(num)
calendar_df['int_price']=calendar_df.price.apply(str_to_int)
f_df=calendar_df.loc[(calendar_df.new_date>=20200101) & (calendar_df.new_date<=20200301) & \
                     (calendar_df.available=='t'),['listing_id','int_price']]
f_df=f_df.groupby(by=['listing_id'])['int_price'].mean().agg([np.mean,np.std])

print(f_df)

mean    254.778227
std     684.755050
Name: int_price, dtype: float64


### Question 7: For reviews that are written in Jan, 2016, what are the most popular ten words except stopping words? What about reviews written in March, 2017 and April, 2018?
**Hint**: You need to use NTLK stopping words to find the stopping words in Python. You also need to remove punctuation and numbers

**Question 7 Answer:**

The most popular ten words in 2016-01 are: 'great', 'stay', 'place', 'clean', 'location', 'house', 'us', 'nice', 'would', 'host'; 
The most popular ten words in 2017-03 are: 'great', 'place', 'stay', 'location', 'clean', 'nice', 'would', 'host', 'house', 'comfortable'; 
The most popular ten words in 2018-04 are: 'great', 'place', 'stay', 'location', 'clean', 'would', 'host', 'nice', 'house', 'everything'

In [19]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = stopwords.words('english')
import string
punc=set(string.punctuation)

reviews_df=pd.read_csv('reviews.csv')
number=['1','2','3','4','5','6','7','8','9','0','']

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/victorhddd/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [20]:
def review(time,df):
    reviews_list=[]
    for index,rows in df.iterrows():
        if time in rows['date']:
            comment=str(rows['comments'])
            comment_new=''
            for i in range(len(comment)):
                if comment[i] not in number:
                    if comment[i] not in punc:
                        comment_new+=comment[i].lower()
                    else:
                        comment_new+=' '
            comment_list=comment_new.strip().split(' ')
            for t in comment_list:
                if t not in stop_words:
                    reviews_list.append(t)
    return reviews_list

In [21]:
def word_count_10(word_list):
    word_dict={}
    for i in word_list:
        if i in word_dict.keys():
            word_dict[i]+=1
        else:
            word_dict[i]=1
    if '' in word_dict.keys():
        del word_dict['']
    word_dict_sorted = sorted( word_dict.items(),key = lambda x:x[1],reverse = True)
    
    word_df=pd.DataFrame.from_dict(word_dict_sorted[0:10])
    word_df.columns=['word','count']
    return word_df

In [22]:
reviews_2016_01=review('2016-01',reviews_df)
reviews_2017_03=review('2017-03',reviews_df)
reviews_2018_04=review('2018-04',reviews_df)

In [18]:
print(get_word(reviews_2016_01))

NameError: name 'get_word' is not defined

In [ ]:
print(get_word(reviews_2017_03))

In [ ]:
print(get_word(reviews_2018_04))

### Question 8: Which five zipcode has the highest average listing price and has at least 30 listings (again only considering available dates) between 2020-01-01 to 2020-02-01 (inclusive)? What are these listing prices? What are the number of active listings and number of hosts in these top five zipcodes (a listing is active if it has at least one available date in the calendar data)?

**Question 8 Answer:**

The five zipcodes with the highest average listing price and has at least 30 listings between 2020-01-01 to 2020-02-01 (inclusive) are 90210, 90077, 90265, 90069, 91436. The average listing price for these zipcodes are 1963.557367, 1909.066130, 1559.605010, 998.113153, 742.660019 respectively. The number of active listings are 278, 74, 329, 423 and 40 respectively. The number of hosts are 173, 48, 221, 305 and 33 respectively.

In [23]:
# You need to provide the code to answer the previous quesiton
from pandasql import sqldf

g_df=calendar_df.loc[(calendar_df.new_date>=20200101) & (calendar_df.new_date<=20200201) \
                     & (calendar_df.available=='t'),['listing_id','int_price']]
h_df=g_df.merge(listing_df, how='left', left_on='listing_id', right_on='id')
i_df=sqldf('SELECT zipcode, AVG(int_price), COUNT(DISTINCT id), COUNT(DISTINCT host_id) \
FROM h_df GROUP BY zipcode HAVING COUNT(DISTINCT id)>=30 ORDER BY AVG(int_price) DESC LIMIT 5')
i_df

zipcode  AVG(int_price)  COUNT(DISTINCT id)  COUNT(DISTINCT host_id)
0   90210     1963.557367                 278                      173
1   90077     1909.066130                  74                       48
2   90265     1559.605010                 329                      221
3   90069      998.113153                 423                      305
4   91436      742.660019                  40                       33

### Question 9: Focusing on the data from 2020-01-01 to 2020-04-01 (inclusive), what are five zipcodes that have at least 30 listings and have the largest absolute difference between the average prices on weekends versus the average prices on weekdays? (Weekends = Saturday and Sunday). Please give the zipcodes as well as the listing prices
**Question 9 Answer:**

The five zipcodes that have at least 30 listings and have the largest absolute difference between the average prices on weekends versus the average prices on weekdays are 90265, 91325, 91436, 90293 and 90048. The absolute differences are 24.733803, 15.341341, 12.383224, 11.918970 and 10.531587 respectively.

In [ ]:
# You need to provide the code to answer the previous quesiton
calendar_df['date_parsed'] = pd.to_datetime(calendar_df['date'])
calendar_df['weekday']=calendar_df.date_parsed.apply(lambda x: 'Weekday' if x.weekday()<=4 else 'Weekend')
j_df=calendar_df.loc[(calendar_df.new_date>=20200101) & (calendar_df.new_date<=20200401) & \
                     (calendar_df.available=='t'),['listing_id','int_price','weekday','date_parsed']]
k_df=j_df.merge(listing_df, how='left', left_on='listing_id', right_on='id')
l_df=sqldf('SELECT zipcode FROM k_df GROUP BY zipcode HAVING COUNT(DISTINCT id)>=30')

In [ ]:
zipcode_list=l_df['zipcode'].tolist()
k_df['bool_zipcode']=k_df.zipcode.apply(lambda x: 1 if x in zipcode_list else 0)
m_df=k_df.loc[k_df['bool_zipcode'] ==1,:].groupby(by=['zipcode','weekday']).int_price.mean().unstack()
m_df=m_df.reset_index()
m_df['abs_price']=m_df.apply(lambda x: abs(x['Weekday']-x['Weekend']),axis=1)
m_df.sort_values(by=['abs_price'],ascending=False)[:5]

### Question 10: What is the average and standard deviation of the daily total capacity at Airbnb Los Angeles from 2020-01-01 to 2020-04-01? The daily total capacity in a day is the number of beds that are available in that given date. What is the average and standard deviation of the daily price per bed at Airbnb Los Angeles from 2020-01-01 to 2020-04-01?
**Question 10 Answer:**

The average and standard deviation of the daily total capacity at Airbnb Los Angeles from 2020-01-01 to 2020-04-01 is 46995.228261 and 4980.641316. The average and standard deviation of the daily price per bed at Airbnb Los Angeles from 2020-01-01 to 2020-04-01 is 124.113884 and 5.626011.

In [ ]:
# You need to provide the code to answer the previous quesiton
n_df=k_df.groupby(by=['date_parsed'])['beds','int_price'].\
apply(lambda x: pd.Series({'Capacity':x['beds'].sum(),'Price':x['int_price'].sum()/x['beds'].sum()}))
n_df.describe()

## Part 2 (15 Points):

In this part, you need to find **5** interesting business questions out of the datasets. You then need to write Python code to answer the questions. Last, you need to write a 200-word summary of your answers and business insights you get from ansewr these 5 questions baed on your code. You will be evaluated based on the following criterion:

1. You need to ask three business-relevant questions (2 points)
2. You need to answer these three questions using Python and the datasets (1 points)
3. You have at least **5** graphs to visualize your insights (2 points)
4. Your executive summary of your answers are well-written and make sense (5 points)
5. Your business insights are very interesting and the report is creative (5 points)


**(You need to use this cell to write your 5 questions)**

**Question 1:**

**Question 2:**

**Question 3:**

**Question 4:**

**Question 5:**


In [ ]:
# Your code to answer Question 1

In [105]:
# Your code to answer Question 2

In [ ]:
# Your code to answer Question 3

In [ ]:
# Your code to answer Question 4

In [ ]:
# Your code to answer Question 5

## Executive Summary
**(You need to use this cell to write your executive summary)**

First of all, from 2016 to 2019, the most frequently mentioned words in comments with scores Below 90 were room something and room something. Surprisingly, we found that in 2019, customers were more concerned about cleaning bathrooms and cleaning, which means that customers have been more concerned about cleaning recently. And two,. We were surprised by the much higher average prices for homes with more stringent cancellation policies, but it makes sense, because the more expensive the homes, the higher the cancellation costs, and therefore the more stringent cancellation policies are needed. The result shows that it is not the cancellation policy but the contrary policy that affects the price. And three... The top 10 regions have low average ratings and prices, while the top 10 regions are hardly listed. (34.0,-118.9) is the most respected but also the most expensive area to go in. (34.7,-118.1) and (34.3,-118.3) are unpopular, but good for those hoping for high ratings and low prices. Size (34.0,-118.3 ~-118.5) and size (34.1,-118.1 ~-118.4) are the most popular places for Airbnb to go public, located in Downtown Los Angeles. Then, all of the detailed ratings will affect the overall score, which is statistically significant. Accuracy and value are two of the most important factors for customers to evaluate their experience. Finally, if the host responds within a day, it does not affect the overall score and communication score.